import * as approvals from "./approvals.js";
import * as execApprovals from "./exec-approvals.js";
import * as questions from "./questions.js";

export const ApprovalProtocolSchemas = {
  ApprovalKind: approvals.ApprovalKindSchema,
  ApprovalDecision: approvals.ApprovalDecisionSchema,
  ApprovalAllowDecision: approvals.ApprovalAllowDecisionSchema,
  ApprovalAllowedReason: approvals.ApprovalAllowedReasonSchema,
  ApprovalDeniedReason: approvals.ApprovalDeniedReasonSchema,
  ApprovalExpiredReason: approvals.ApprovalExpiredReasonSchema,
  ApprovalCancelledReason: approvals.ApprovalCancelledReasonSchema,
  PluginApprovalSeverity: approvals.PluginApprovalSeveritySchema,
  ExecApprovalPresentation: approvals.ExecApprovalPresentationSchema,
  PluginApprovalPresentation: approvals.PluginApprovalPresentationSchema,
  SystemAgentApprovalPresentation: approvals.SystemAgentApprovalPresentationSchema,
  ApprovalPresentation: approvals.ApprovalPresentationSchema,
  PendingApprovalSnapshot: approvals.PendingApprovalSnapshotSchema,
  AllowedApprovalSnapshot: approvals.AllowedApprovalSnapshotSchema,
  DeniedApprovalSnapshot: approvals.DeniedApprovalSnapshotSchema,
  ExpiredApprovalSnapshot: approvals.ExpiredApprovalSnapshotSchema,
  CancelledApprovalSnapshot: approvals.CancelledApprovalSnapshotSchema,
  ApprovalSnapshot: approvals.ApprovalSnapshotSchema,
  ApprovalTerminalReason: approvals.ApprovalTerminalReasonSchema,
  TerminalApprovalSnapshot: approvals.TerminalApprovalSnapshotSchema,
  ApprovalGetParams: approvals.ApprovalGetParamsSchema,
  ApprovalGetResult: approvals.ApprovalGetResultSchema,
  ApprovalHistoryParams: approvals.ApprovalHistoryParamsSchema,
  ApprovalHistoryResult: approvals.ApprovalHistoryResultSchema,
  ApprovalResolveParams: approvals.ApprovalResolveParamsSchema,
  ApprovalResolveResult: approvals.ApprovalResolveResultSchema,
  PendingSessionApprovalEvent: approvals.PendingSessionApprovalEventSchema,
  TerminalSessionApprovalEvent: approvals.TerminalSessionApprovalEventSchema,
  SessionApprovalEvent: approvals.SessionApprovalEventSchema,
  SessionApprovalReplay: approvals.SessionApprovalReplaySchema,
  ExecApprovalsGetParams: execApprovals.ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: execApprovals.ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: execApprovals.ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSnapshot: execApprovals.ExecApprovalsNodeSnapshotSchema,
  ExecApprovalsNodeSetParams: execApprovals.ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: execApprovals.ExecApprovalsSnapshotSchema,
  ExecApprovalGetParams: execApprovals.ExecApprovalGetParamsSchema,
  ExecApprovalRequestParams: execApprovals.ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: execApprovals.ExecApprovalResolveParamsSchema,
  QuestionOption: questions.QuestionOptionSchema,
  Question: questions.QuestionSchema,
  QuestionRequestQuestion: questions.QuestionRequestQuestionSchema,
  QuestionAnswers: questions.QuestionAnswersSchema,
  QuestionStatus: questions.QuestionStatusSchema,
  QuestionRecord: questions.QuestionRecordSchema,
  QuestionRequestParams: questions.QuestionRequestParamsSchema,
  QuestionRequestResult: questions.QuestionRequestResultSchema,
  QuestionWaitAnswerParams: questions.QuestionWaitAnswerParamsSchema,
  QuestionWaitAnswerResult: questions.QuestionWaitAnswerResultSchema,
  QuestionResolveParams: questions.QuestionResolveParamsSchema,
  QuestionResolveResult: questions.QuestionResolveResultSchema,
  QuestionGetParams: questions.QuestionGetParamsSchema,
  QuestionGetResult: questions.QuestionGetResultSchema,
  QuestionListParams: questions.QuestionListParamsSchema,
  QuestionListResult: questions.QuestionListResultSchema,
  // QuestionRequestedEvent is a TS-only alias of QuestionRecord; registering both
  // names makes native codegen reference a type it never emits.
  QuestionResolvedEvent: questions.QuestionResolvedEventSchema,
} as const;
