import * as agent from "./agent.js";
import * as environments from "./environments.js";
import * as fsSchemas from "./fs.js";
import * as systemInfo from "./system-info.js";
import * as worktrees from "./worktrees.js";

export const AgentControlProtocolSchemas = {
  EnvironmentStatus: environments.EnvironmentStatusSchema,
  WorkerEnvironmentState: environments.WorkerEnvironmentStateSchema,
  WorkerTunnelStatus: environments.WorkerTunnelStatusSchema,
  WorkerEnvironmentMetadata: environments.WorkerEnvironmentMetadataSchema,
  EnvironmentSummary: environments.EnvironmentSummarySchema,
  EnvironmentsCreateParams: environments.EnvironmentsCreateParamsSchema,
  EnvironmentsCreateResult: environments.EnvironmentsCreateResultSchema,
  EnvironmentsDestroyParams: environments.EnvironmentsDestroyParamsSchema,
  EnvironmentsDestroyResult: environments.EnvironmentsDestroyResultSchema,
  EnvironmentsListParams: environments.EnvironmentsListParamsSchema,
  EnvironmentsListResult: environments.EnvironmentsListResultSchema,
  EnvironmentsStatusParams: environments.EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResult: environments.EnvironmentsStatusResultSchema,
  SystemInfoParams: systemInfo.SystemInfoParamsSchema,
  SystemInfoResult: systemInfo.SystemInfoResultSchema,
  AgentEvent: agent.AgentEventSchema,
  ConversationSendParams: agent.ConversationSendParamsSchema,
  ConversationSendResult: agent.ConversationSendResultSchema,
  ConversationListItem: agent.ConversationListItemSchema,
  ConversationListParams: agent.ConversationListParamsSchema,
  ConversationListResult: agent.ConversationListResultSchema,
  ConversationTurnCancelParams: agent.ConversationTurnCancelParamsSchema,
  ConversationTurnCancelResult: agent.ConversationTurnCancelResultSchema,
  ConversationTurnParams: agent.ConversationTurnParamsSchema,
  ConversationTurnReply: agent.ConversationTurnReplySchema,
  ConversationTurnResult: agent.ConversationTurnResultSchema,
  MessageActionParams: agent.MessageActionParamsSchema,
  SendParams: agent.SendParamsSchema,
  PollParams: agent.PollParamsSchema,
  AgentParams: agent.AgentParamsSchema,
  AgentIdentityParams: agent.AgentIdentityParamsSchema,
  AgentIdentityResult: agent.AgentIdentityResultSchema,
  AgentWaitParams: agent.AgentWaitParamsSchema,
  WakeParams: agent.WakeParamsSchema,
  WorktreeRecord: worktrees.WorktreeRecordSchema,
  WorktreesListParams: worktrees.WorktreesListParamsSchema,
  WorktreesListResult: worktrees.WorktreesListResultSchema,
  WorktreesCreateParams: worktrees.WorktreesCreateParamsSchema,
  WorktreesRemoveParams: worktrees.WorktreesRemoveParamsSchema,
  WorktreesRemoveResult: worktrees.WorktreesRemoveResultSchema,
  WorktreesRestoreParams: worktrees.WorktreesRestoreParamsSchema,
  WorktreesGcParams: worktrees.WorktreesGcParamsSchema,
  WorktreesGcResult: worktrees.WorktreesGcResultSchema,
  WorktreeBranch: worktrees.WorktreeBranchSchema,
  WorktreeRepositoryStatus: worktrees.WorktreeRepositoryStatusSchema,
  WorktreesBranchesParams: worktrees.WorktreesBranchesParamsSchema,
  WorktreesBranchesResult: worktrees.WorktreesBranchesResultSchema,
  FsDirEntry: fsSchemas.FsDirEntrySchema,
  FsListDirParams: fsSchemas.FsListDirParamsSchema,
  FsListDirResult: fsSchemas.FsListDirResultSchema,
} as const;
