import * as auditActivity from "./audit-activity.js";
import * as audit from "./audit.js";
import * as config from "./config.js";
import * as openclaw from "./openclaw.js";
import * as taskSuggestions from "./task-suggestions.js";
import * as tasks from "./tasks.js";
import * as wizard from "./wizard.js";

export const OperationsProtocolSchemas = {
  AuditActivityAgentRunV1: auditActivity.AuditActivityAgentRunV1Schema,
  AuditActivityToolActionV1: auditActivity.AuditActivityToolActionV1Schema,
  AuditActivityInboundMessageV1: auditActivity.AuditActivityInboundMessageV1Schema,
  AuditActivityOutboundMessageV1: auditActivity.AuditActivityOutboundMessageV1Schema,
  AuditActivityEventV1: auditActivity.AuditActivityEventV1Schema,
  AuditActivityListParams: auditActivity.AuditActivityListParamsSchema,
  AuditActivityListResult: auditActivity.AuditActivityListResultSchema,
  AuditEvent: audit.AuditEventSchema,
  AuditListParams: audit.AuditListParamsSchema,
  AuditListResult: audit.AuditListResultSchema,
  TaskSuggestion: taskSuggestions.TaskSuggestionSchema,
  TaskSuggestionEvent: taskSuggestions.TaskSuggestionEventSchema,
  TaskSuggestionResolution: taskSuggestions.TaskSuggestionResolutionSchema,
  TaskSuggestionsAcceptParams: taskSuggestions.TaskSuggestionsAcceptParamsSchema,
  TaskSuggestionsAcceptResult: taskSuggestions.TaskSuggestionsAcceptResultSchema,
  TaskSuggestionsCreateParams: taskSuggestions.TaskSuggestionsCreateParamsSchema,
  TaskSuggestionsCreateResult: taskSuggestions.TaskSuggestionsCreateResultSchema,
  TaskSuggestionsDismissParams: taskSuggestions.TaskSuggestionsDismissParamsSchema,
  TaskSuggestionsDismissResult: taskSuggestions.TaskSuggestionsDismissResultSchema,
  TaskSuggestionsListParams: taskSuggestions.TaskSuggestionsListParamsSchema,
  TaskSuggestionsListResult: taskSuggestions.TaskSuggestionsListResultSchema,
  TaskSummary: tasks.TaskSummarySchema,
  TasksListParams: tasks.TasksListParamsSchema,
  TasksListResult: tasks.TasksListResultSchema,
  TasksGetParams: tasks.TasksGetParamsSchema,
  TasksGetResult: tasks.TasksGetResultSchema,
  TasksCancelParams: tasks.TasksCancelParamsSchema,
  TasksCancelResult: tasks.TasksCancelResultSchema,
  TasksRecoveryParams: tasks.TasksRecoveryParamsSchema,
  TasksRecoveryResult: tasks.TasksRecoveryResultSchema,
  ConfigGetParams: config.ConfigGetParamsSchema,
  ConfigSetParams: config.ConfigSetParamsSchema,
  ConfigApplyParams: config.ConfigApplyParamsSchema,
  ConfigPatchParams: config.ConfigPatchParamsSchema,
  ConfigSchemaParams: config.ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: config.ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: config.ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: config.ConfigSchemaLookupResultSchema,
  SystemAgentChatParams: openclaw.SystemAgentChatParamsSchema,
  SystemAgentChatResult: openclaw.SystemAgentChatResultSchema,
  SystemAgentChatHistoryParams: openclaw.SystemAgentChatHistoryParamsSchema,
  SystemAgentChatHistoryTurn: openclaw.SystemAgentChatHistoryTurnSchema,
  SystemAgentChatHistoryResult: openclaw.SystemAgentChatHistoryResultSchema,
  SystemChangeEntry: openclaw.SystemChangeEntrySchema,
  SystemChangeKind: openclaw.SystemChangeKindSchema,
  SystemChangeSource: openclaw.SystemChangeSourceSchema,
  SystemChangesListParams: openclaw.SystemChangesListParamsSchema,
  SystemChangesListResult: openclaw.SystemChangesListResultSchema,
  SystemAgentSetupDetectParams: openclaw.SystemAgentSetupDetectParamsSchema,
  SystemAgentSetupDetectResult: openclaw.SystemAgentSetupDetectResultSchema,
  SystemAgentSetupVerifyParams: openclaw.SystemAgentSetupVerifyParamsSchema,
  SystemAgentSetupVerifyResult: openclaw.SystemAgentSetupVerifyResultSchema,
  SystemAgentSetupActivateParams: openclaw.SystemAgentSetupActivateParamsSchema,
  SystemAgentSetupActivateResult: openclaw.SystemAgentSetupActivateResultSchema,
  SystemAgentSetupAuthStartParams: openclaw.SystemAgentSetupAuthStartParamsSchema,
  SystemAgentSetupAuthStartResult: openclaw.SystemAgentSetupAuthStartResultSchema,
  WizardStartParams: wizard.WizardStartParamsSchema,
  WizardNextParams: wizard.WizardNextParamsSchema,
  WizardCancelParams: wizard.WizardCancelParamsSchema,
  WizardStatusParams: wizard.WizardStatusParamsSchema,
  WizardStep: wizard.WizardStepSchema,
  WizardNextResult: wizard.WizardNextResultSchema,
  WizardStartResult: wizard.WizardStartResultSchema,
  WizardStatusResult: wizard.WizardStatusResultSchema,
} as const;
