import * as agentsModelsSkills from "./agents-models-skills.js";
import * as board from "./board.js";

export const BoardProtocolSchemas = {
  BoardTab: board.BoardTabSchema,
  BoardWidget: board.BoardWidgetSchema,
  BoardWidgetDeclared: board.BoardWidgetDeclaredSchema,
  BoardSnapshot: board.BoardSnapshotSchema,
  BoardTabCreateOp: board.BoardTabCreateOpSchema,
  BoardTabUpdateOp: board.BoardTabUpdateOpSchema,
  BoardTabDeleteOp: board.BoardTabDeleteOpSchema,
  BoardTabsReorderOp: board.BoardTabsReorderOpSchema,
  BoardWidgetMoveOp: board.BoardWidgetMoveOpSchema,
  BoardWidgetResizeOp: board.BoardWidgetResizeOpSchema,
  BoardWidgetRemoveOp: board.BoardWidgetRemoveOpSchema,
  BoardOp: board.BoardOpSchema,
  BoardMcpAppDescriptor: board.BoardMcpAppDescriptorSchema,
  BoardWidgetHtmlContent: board.BoardWidgetHtmlContentSchema,
  BoardWidgetMcpAppContent: board.BoardWidgetMcpAppContentSchema,
  BoardWidgetMcpAppPutContent: board.BoardWidgetMcpAppPutContentSchema,
  BoardWidgetPluginContent: board.BoardWidgetPluginContentSchema,
  BoardCanvasDocumentSource: board.BoardCanvasDocumentSourceSchema,
  BoardWidgetContent: board.BoardWidgetContentSchema,
  BoardWidgetPutContent: board.BoardWidgetPutContentSchema,
  BoardWidgetGeneratedIdentity: board.BoardWidgetGeneratedIdentitySchema,
  BoardGetParams: board.BoardGetParamsSchema,
  BoardUpdateParams: board.BoardUpdateParamsSchema,
  BoardWidgetPutParams: board.BoardWidgetPutParamsSchema,
  BoardWidgetPutResult: board.BoardWidgetPutResultSchema,
  BoardWidgetGrantParams: board.BoardWidgetGrantParamsSchema,
  BoardWidgetAppViewParams: board.BoardWidgetAppViewParamsSchema,
  BoardWidgetAppViewResult: board.BoardWidgetAppViewResultSchema,
  BoardEventParams: board.BoardEventParamsSchema,
  BoardPromptAuthorizeParams: board.BoardPromptAuthorizeParamsSchema,
  BoardDataReadParams: board.BoardDataReadParamsSchema,
  BoardActionParams: board.BoardActionParamsSchema,
  BoardChangedEvent: board.BoardChangedEventSchema,
  BoardFocusTabCommand: board.BoardFocusTabCommandSchema,
  BoardSetChatDockCommand: board.BoardSetChatDockCommandSchema,
  BoardCommand: board.BoardCommandSchema,
  BoardCommandEvent: board.BoardCommandEventSchema,
  AuthProbeStatus: agentsModelsSkills.AuthProbeStatusSchema,
} as const;
