import * as config from "./config.js";
import * as devices from "./devices.js";
import * as frames from "./frames.js";
import * as hooks from "./hooks.js";
import * as logsChat from "./logs-chat.js";
import * as pluginApprovals from "./plugin-approvals.js";
import * as plugins from "./plugins.js";

export const PluginLifecycleProtocolSchemas = {
  HooksStatusParams: hooks.HooksStatusParamsSchema,
  PluginApprovalRequestParams: pluginApprovals.PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: pluginApprovals.PluginApprovalResolveParamsSchema,
  PluginCatalogClawHubInstall: plugins.PluginCatalogClawHubInstallSchema,
  PluginCatalogEntry: plugins.PluginCatalogEntrySchema,
  PluginCatalogInstallAction: plugins.PluginCatalogInstallActionSchema,
  PluginCatalogOfficialInstall: plugins.PluginCatalogOfficialInstallSchema,
  PluginControlUiDescriptor: plugins.PluginControlUiDescriptorSchema,
  PluginSearchPackage: plugins.PluginSearchPackageSchema,
  PluginSearchResultEntry: plugins.PluginSearchResultEntrySchema,
  PluginsInstallParams: plugins.PluginsInstallParamsSchema,
  PluginsInstallResult: plugins.PluginsInstallResultSchema,
  PluginsListParams: plugins.PluginsListParamsSchema,
  PluginsListResult: plugins.PluginsListResultSchema,
  PluginsRefreshParams: plugins.PluginsRefreshParamsSchema,
  PluginsRefreshResult: plugins.PluginsRefreshResultSchema,
  PluginsSearchParams: plugins.PluginsSearchParamsSchema,
  PluginsSearchResult: plugins.PluginsSearchResultSchema,
  PluginsSessionActionFailureResult: plugins.PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParams: plugins.PluginsSessionActionParamsSchema,
  PluginsSessionActionResult: plugins.PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResult: plugins.PluginsSessionActionSuccessResultSchema,
  PluginsSetEnabledParams: plugins.PluginsSetEnabledParamsSchema,
  PluginsSetEnabledResult: plugins.PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParams: plugins.PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResult: plugins.PluginsUiDescriptorsResultSchema,
  PluginsUninstallParams: plugins.PluginsUninstallParamsSchema,
  PluginsUninstallResult: plugins.PluginsUninstallResultSchema,
  DevicePairListParams: devices.DevicePairListParamsSchema,
  DevicePairApproveParams: devices.DevicePairApproveParamsSchema,
  DevicePairRejectParams: devices.DevicePairRejectParamsSchema,
  DevicePairRemoveParams: devices.DevicePairRemoveParamsSchema,
  DevicePairSetupCodeParams: devices.DevicePairSetupCodeParamsSchema,
  DevicePairSetupCodeResult: devices.DevicePairSetupCodeResultSchema,
  DevicePairRenameParams: devices.DevicePairRenameParamsSchema,
  DeviceTokenRotateParams: devices.DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: devices.DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: devices.DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: devices.DevicePairResolvedEventSchema,
  ChatHistoryParams: logsChat.ChatHistoryParamsSchema,
  ChatMetadataParams: logsChat.ChatMetadataParamsSchema,
  ChatMessageGetParams: logsChat.ChatMessageGetParamsSchema,
  ChatMessageGetResult: logsChat.ChatMessageGetResultSchema,
  ChatToolTitlesParams: logsChat.ChatToolTitlesParamsSchema,
  ChatToolTitlesResult: logsChat.ChatToolTitlesResultSchema,
  ChatSendParams: logsChat.ChatSendParamsSchema,
  ChatAbortParams: logsChat.ChatAbortParamsSchema,
  ChatInjectParams: logsChat.ChatInjectParamsSchema,
  ChatRunStartupPhase: logsChat.ChatRunStartupPhaseSchema,
  ChatStatusEvent: logsChat.ChatStatusEventSchema,
  ChatDeltaEvent: logsChat.ChatDeltaEventSchema,
  ChatFinalEvent: logsChat.ChatFinalEventSchema,
  ChatAbortedEvent: logsChat.ChatAbortedEventSchema,
  ChatErrorEvent: logsChat.ChatErrorEventSchema,
  ChatEvent: logsChat.ChatEventSchema,
  UpdateStatusParams: config.UpdateStatusParamsSchema,
  UpdateRunParams: config.UpdateRunParamsSchema,
  TickEvent: frames.TickEventSchema,
  ShutdownEvent: frames.ShutdownEventSchema,
} as const;
