import * as channelPairing from "./channel-pairing.js";
import * as channels from "./channels.js";
import * as talkMarks from "./talk-marks.js";

export const ChannelProtocolSchemas = {
  TalkModeParams: channels.TalkModeParamsSchema,
  TalkEvent: channels.TalkEventSchema,
  TalkCatalogParams: channels.TalkCatalogParamsSchema,
  TalkCatalogResult: channels.TalkCatalogResultSchema,
  TalkClientCreateParams: channels.TalkClientCreateParamsSchema,
  TalkClientCreateResult: channels.TalkClientCreateResultSchema,
  TalkClientCloseParams: channels.TalkClientCloseParamsSchema,
  TalkClientMutationResult: channels.TalkClientMutationResultSchema,
  TalkClientSteerParams: channels.TalkClientSteerParamsSchema,
  TalkAgentControlResult: channels.TalkAgentControlResultSchema,
  TalkClientToolCallParams: channels.TalkClientToolCallParamsSchema,
  TalkClientToolCallResult: channels.TalkClientToolCallResultSchema,
  TalkClientTranscriptParams: channels.TalkClientTranscriptParamsSchema,
  TalkConfigParams: channels.TalkConfigParamsSchema,
  TalkConfigResult: channels.TalkConfigResultSchema,
  TalkSessionAppendAudioParams: channels.TalkSessionAppendAudioParamsSchema,
  TalkSessionAcknowledgeMarkParams: talkMarks.TalkSessionAcknowledgeMarkParamsSchema,
  TalkSessionCancelOutputParams: channels.TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParams: channels.TalkSessionCancelTurnParamsSchema,
  TalkSessionCreateParams: channels.TalkSessionCreateParamsSchema,
  TalkSessionCreateResult: channels.TalkSessionCreateResultSchema,
  TalkSessionJoinParams: channels.TalkSessionJoinParamsSchema,
  TalkSessionJoinResult: channels.TalkSessionJoinResultSchema,
  TalkSessionTurnParams: channels.TalkSessionTurnParamsSchema,
  TalkSessionTurnResult: channels.TalkSessionTurnResultSchema,
  TalkSessionSteerParams: channels.TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParams: channels.TalkSessionSubmitToolResultParamsSchema,
  TalkSessionCloseParams: channels.TalkSessionCloseParamsSchema,
  TalkSessionOkResult: channels.TalkSessionOkResultSchema,
  TalkSpeakParams: channels.TalkSpeakParamsSchema,
  TalkSpeakResult: channels.TalkSpeakResultSchema,
  TtsSpeakParams: channels.TtsSpeakParamsSchema,
  TtsSpeakResult: channels.TtsSpeakResultSchema,
  ChannelsStatusParams: channels.ChannelsStatusParamsSchema,
  ChannelsStatusResult: channels.ChannelsStatusResultSchema,
  ChannelsPairingListParams: channelPairing.ChannelsPairingListParamsSchema,
  ChannelsPairingListResult: channelPairing.ChannelsPairingListResultSchema,
  ChannelsPairingApproveParams: channelPairing.ChannelsPairingApproveParamsSchema,
  ChannelsPairingApproveResult: channelPairing.ChannelsPairingApproveResultSchema,
  ChannelsPairingDismissParams: channelPairing.ChannelsPairingDismissParamsSchema,
  ChannelsPairingDismissResult: channelPairing.ChannelsPairingDismissResultSchema,
  ChannelsStartParams: channels.ChannelsStartParamsSchema,
  ChannelsStopParams: channels.ChannelsStopParamsSchema,
  ChannelsLogoutParams: channels.ChannelsLogoutParamsSchema,
  WebLoginStartParams: channels.WebLoginStartParamsSchema,
  WebLoginWaitParams: channels.WebLoginWaitParamsSchema,
} as const;
