import * as agentsModelsSkills from "./agents-models-skills.js";
import * as agentsWorkspace from "./agents-workspace.js";
import * as artifacts from "./artifacts.js";
import * as commands from "./commands.js";
import * as skillWorkshop from "./skill-protocol-schemas.js";

export const AgentSkillProtocolSchemas = {
  AgentKind: agentsModelsSkills.AgentKindSchema,
  AgentSummary: agentsModelsSkills.AgentSummarySchema,
  AgentsCreateParams: agentsModelsSkills.AgentsCreateParamsSchema,
  AgentsCreateResult: agentsModelsSkills.AgentsCreateResultSchema,
  AgentsUpdateParams: agentsModelsSkills.AgentsUpdateParamsSchema,
  AgentsUpdateResult: agentsModelsSkills.AgentsUpdateResultSchema,
  AgentsDeleteParams: agentsModelsSkills.AgentsDeleteParamsSchema,
  AgentsDeleteResult: agentsModelsSkills.AgentsDeleteResultSchema,
  AgentsFileEntry: agentsModelsSkills.AgentsFileEntrySchema,
  AgentsFilesListParams: agentsModelsSkills.AgentsFilesListParamsSchema,
  AgentsFilesListResult: agentsModelsSkills.AgentsFilesListResultSchema,
  AgentsFilesGetParams: agentsModelsSkills.AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: agentsModelsSkills.AgentsFilesGetResultSchema,
  AgentsFilesSetParams: agentsModelsSkills.AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: agentsModelsSkills.AgentsFilesSetResultSchema,
  AgentsWorkspaceEntry: agentsWorkspace.AgentsWorkspaceEntrySchema,
  AgentsWorkspaceFile: agentsWorkspace.AgentsWorkspaceFileSchema,
  AgentsWorkspaceListParams: agentsWorkspace.AgentsWorkspaceListParamsSchema,
  AgentsWorkspaceListResult: agentsWorkspace.AgentsWorkspaceListResultSchema,
  AgentsWorkspaceGetParams: agentsWorkspace.AgentsWorkspaceGetParamsSchema,
  AgentsWorkspaceGetResult: agentsWorkspace.AgentsWorkspaceGetResultSchema,
  ArtifactSummary: artifacts.ArtifactSummarySchema,
  ArtifactsListParams: artifacts.ArtifactsListParamsSchema,
  ArtifactsListResult: artifacts.ArtifactsListResultSchema,
  ArtifactsGetParams: artifacts.ArtifactsGetParamsSchema,
  ArtifactsGetResult: artifacts.ArtifactsGetResultSchema,
  ArtifactsDownloadParams: artifacts.ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResult: artifacts.ArtifactsDownloadResultSchema,
  AgentsListParams: agentsModelsSkills.AgentsListParamsSchema,
  AgentsListResult: agentsModelsSkills.AgentsListResultSchema,
  ModelChoice: agentsModelsSkills.ModelChoiceSchema,
  ModelsAuthLogoutParams: agentsModelsSkills.ModelsAuthLogoutParamsSchema,
  ModelsAuthStatusParams: agentsModelsSkills.ModelsAuthStatusParamsSchema,
  ModelsListParams: agentsModelsSkills.ModelsListParamsSchema,
  ModelsListResult: agentsModelsSkills.ModelsListResultSchema,
  ModelsProbeParams: agentsModelsSkills.ModelsProbeParamsSchema,
  ModelsProbeTargetResult: agentsModelsSkills.ModelsProbeTargetResultSchema,
  ModelsProbeResult: agentsModelsSkills.ModelsProbeResultSchema,
  CommandEntry: commands.CommandEntrySchema,
  CommandsListParams: commands.CommandsListParamsSchema,
  CommandsListResult: commands.CommandsListResultSchema,
  SkillsStatusParams: agentsModelsSkills.SkillsStatusParamsSchema,
  ToolsCatalogParams: agentsModelsSkills.ToolsCatalogParamsSchema,
  ToolCatalogProfile: agentsModelsSkills.ToolCatalogProfileSchema,
  ToolCatalogEntry: agentsModelsSkills.ToolCatalogEntrySchema,
  ToolCatalogGroup: agentsModelsSkills.ToolCatalogGroupSchema,
  ToolsCatalogResult: agentsModelsSkills.ToolsCatalogResultSchema,
  ToolsEffectiveParams: agentsModelsSkills.ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: agentsModelsSkills.ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: agentsModelsSkills.ToolsEffectiveGroupSchema,
  ToolsEffectiveNotice: agentsModelsSkills.ToolsEffectiveNoticeSchema,
  ToolsEffectiveResult: agentsModelsSkills.ToolsEffectiveResultSchema,
  ToolsInvokeParams: agentsModelsSkills.ToolsInvokeParamsSchema,
  ToolsInvokeError: agentsModelsSkills.ToolsInvokeErrorSchema,
  ToolsInvokeResult: agentsModelsSkills.ToolsInvokeResultSchema,
  SkillsBinsParams: agentsModelsSkills.SkillsBinsParamsSchema,
  SkillsBinsResult: agentsModelsSkills.SkillsBinsResultSchema,
  SkillsSearchParams: agentsModelsSkills.SkillsSearchParamsSchema,
  SkillsSearchResult: agentsModelsSkills.SkillsSearchResultSchema,
  SkillsDetailParams: agentsModelsSkills.SkillsDetailParamsSchema,
  SkillsDetailResult: agentsModelsSkills.SkillsDetailResultSchema,
  SkillsCuratorActionParams: agentsModelsSkills.SkillsCuratorActionParamsSchema,
  SkillsCuratorActionResult: agentsModelsSkills.SkillsCuratorActionResultSchema,
  SkillsCuratorStatusParams: agentsModelsSkills.SkillsCuratorStatusParamsSchema,
  SkillsCuratorStatusResult: agentsModelsSkills.SkillsCuratorStatusResultSchema,
  ...skillWorkshop.SkillWorkshopProtocolSchemas,
  SkillsProposalInspectParams: agentsModelsSkills.SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResult: agentsModelsSkills.SkillsProposalInspectResultSchema,
  SkillsProposalCreateParams: agentsModelsSkills.SkillsProposalCreateParamsSchema,
  SkillsProposalUpdateParams: agentsModelsSkills.SkillsProposalUpdateParamsSchema,
  SkillsProposalReviseParams: agentsModelsSkills.SkillsProposalReviseParamsSchema,
  SkillsProposalRequestRevisionParams: agentsModelsSkills.SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResult: agentsModelsSkills.SkillsProposalRequestRevisionResultSchema,
  SkillsProposalActionParams: agentsModelsSkills.SkillsProposalActionParamsSchema,
  SkillsProposalApplyResult: agentsModelsSkills.SkillsProposalApplyResultSchema,
  SkillsProposalRecordResult: agentsModelsSkills.SkillsProposalRecordResultSchema,
  SkillsSecurityVerdictsParams: agentsModelsSkills.SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResult: agentsModelsSkills.SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParams: agentsModelsSkills.SkillsSkillCardParamsSchema,
  SkillsSkillCardResult: agentsModelsSkills.SkillsSkillCardResultSchema,
  SkillsUploadBeginParams: agentsModelsSkills.SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParams: agentsModelsSkills.SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParams: agentsModelsSkills.SkillsUploadCommitParamsSchema,
  SkillsInstallParams: agentsModelsSkills.SkillsInstallParamsSchema,
  SkillsUpdateParams: agentsModelsSkills.SkillsUpdateParamsSchema,
} as const;
