/**
 * Stable storage-neutral session and transcript access API.
 *
 * Implementations are split by entry, lifecycle, reset, and transcript ownership.
 * Runtime callers import this barrel instead of storage-specific modules.
 */
export * from "./session-history.js";
export type {
  BranchSessionFromCompactionCheckpointParams,
  DeleteSessionEntryLifecycleParams,
  DeleteSessionEntryLifecycleResult,
  DeletedAgentSessionEntryPurgeParams,
  ExactSessionEntry,
  ForkSessionEntryFromParentTargetParams,
  ForkSessionEntryFromParentTargetResult,
  ForkSessionFromParentTranscriptParams,
  ForkSessionFromParentTranscriptResult,
  LatestTranscriptAssistantText,
  LogicalSessionAccessScope,
  ParentForkedSessionTranscript,
  ReplySessionInitializationCommitContext,
  ReplySessionInitializationCommitResult,
  ReplySessionInitializationSnapshot,
  ResetSessionEntryLifecycleParams,
  ResetSessionEntryLifecycleResult,
  ResolvedSessionEntryAccessTarget,
  ResolvedSessionEntryCandidateTarget,
  ResolvedSessionEntryUpdateContext,
  ResolvedSessionEntryUpdateResult,
  RestoreSessionFromCompactionCheckpointParams,
  SessionAbortTargetContext,
  SessionAbortTargetCutoff,
  SessionAbortTargetIdentity,
  SessionAbortTargetResult,
  SessionAccessScope,
  SessionArchivedTranscriptCleanupRule,
  SessionCompactionCheckpointEntryBuildContext,
  SessionCompactionCheckpointEntryBuilder,
  SessionCompactionCheckpointForkedTranscript,
  SessionCompactionCheckpointMutationResult,
  SessionMessageCutMutationParams,
  SessionMessageCutMutationResult,
  SessionBranchListParams,
  SessionBranchListResult,
  SessionBranchSummary,
  SessionBranchSwitchMutationParams,
  SessionBranchSwitchMutationResult,
  SessionCompactionCheckpointTranscriptForkResult,
  SessionCompactionCheckpointTranscriptForker,
  SessionEntryCandidateAccessScope,
  SessionEntryCreateWithTranscriptContext,
  SessionEntryCreateWithTranscriptOptions,
  SessionEntryCreateWithTranscriptPrepareResult,
  SessionEntryCreateWithTranscriptResult,
  SessionEntryLifecycleMutationResult,
  SessionEntryLifecycleRemoval,
  SessionEntryLifecycleUpsert,
  SessionEntryPatchContext,
  SessionEntryPatchOptions,
  SessionEntryPatchResult,
  SessionEntryReadView,
  SessionEntryReplacement,
  SessionEntryReplacementSnapshot,
  SessionEntryReplacementUpdate,
  SessionEntrySummary,
  SessionEntryTargetPatchScope,
  SessionEntryUpdateOptions,
  SessionLifecycleArchivedTranscript,
  SessionLifecycleArtifactCleanupParams,
  SessionLifecycleArtifactCleanupResult,
  SessionLifecycleStoreTarget,
  SessionLifecycleTranscriptInfo,
  SessionParentForkDecision,
  SessionPatchProjectionContext,
  SessionPatchProjectionFailure,
  SessionPatchProjectionResult,
  SessionPatchProjectionSnapshot,
  SessionPatchProjectionTarget,
  SessionTranscriptAccessScope,
  SessionTranscriptEventRow,
  SessionTranscriptManualTrimPreflightResult,
  SessionTranscriptManualTrimResult,
  SessionTranscriptReadScope,
  SessionTranscriptReadTarget,
  SessionTranscriptRawDeltaLimits,
  SessionTranscriptRawDeltaResult,
  SessionTranscriptRuntimeScope,
  SessionTranscriptRuntimeTarget,
  SessionTranscriptStats,
  SessionTranscriptTurnMessageAppend,
  SessionTranscriptTurnPersistOptions,
  SessionTranscriptTurnPersistResult,
  SessionTranscriptTurnUpdateMode,
  SessionTranscriptTurnWriteContext,
  SessionTranscriptVisibleMessageDeltaLimits,
  SessionTranscriptVisibleMessageDeltaResult,
  SessionTranscriptVisibleMessageEventRow,
  SessionTranscriptWriteLockAccessorContext,
  SessionTranscriptWriteScope,
  SessionTranscriptWriteTransactionContext,
  TemporarySessionMappingPreservationResult,
  TranscriptEvent,
  TranscriptMessageAppendOptions,
  TranscriptMessageAppendResult,
  TranscriptUpdatePayload,
} from "./session-accessor.types.js";
export { onSessionIdentityMutation } from "../../sessions/session-lifecycle-events.js";
export type {
  SessionIdentityMutation,
  SessionIdentityMutationListener,
  SessionIdentityMutationTarget,
} from "../../sessions/session-lifecycle-events.js";
export type {
  SessionTranscriptTurnExpectedState,
  SessionTranscriptTurnLifecyclePatch,
} from "./session-transcript-turn-lifecycle.types.js";
export type {
  RecordInboundSessionMetaParams,
  UpdateSessionLastRouteParams,
} from "./session-accessor.entry-mutation.js";
export {
  countSessionEntryRowsReadOnly,
  copySessionOwnedStateForCanonicalRepair,
  hasSessionEntriesByStatusReadOnly,
  listSessionGenerationIdsForCanonicalRepair,
  clearPluginOwnedSessionState,
  listSessionChildEntriesReadOnly,
  listSessionEntries,
  listSessionEntriesReadOnly,
  listSessionEntriesForCanonicalRepair,
  rehomeSessionDeliveryReferencesForCanonicalRepair,
  rehomeSessionDeliveryReferencesForCanonicalRepairBatch,
  listSessionEntryKeysReadOnly,
  loadExactSessionEntry,
  loadExactSessionEntryReadOnly,
  loadSessionEntry,
  loadSessionEntryReadOnly,
  openSessionEntryReadView,
  patchSessionEntry,
  patchSessionEntryTarget,
  patchSessionEntryWithKey,
  readSessionUpdatedAt,
  replaceSessionEntry,
  replaceSessionEntrySync,
  resolveSessionEntryAccessTarget,
  resolveSessionEntryCandidateTarget,
  resolveSessionEntrySelection,
  updateResolvedSessionEntry,
  upsertSessionEntry,
} from "./session-accessor.entry.js";
export {
  createSessionEntryWithTranscript,
  forkSessionEntryFromParentTarget,
  forkSessionFromParentTranscript,
  markSessionAbortTarget,
  recordInboundSessionMeta,
  resolveSessionAbortTarget,
  resolveSessionParentForkDecision,
  updateSessionEntry,
  updateSessionLastRoute,
} from "./session-accessor.entry-mutation.js";
export {
  applySessionEntryLifecycleMutation,
  applySessionEntryReplacements,
  applySessionPatchProjection,
  applySessionStoreProjection,
  branchSessionFromCompactionCheckpoint,
  cleanupPluginHostSessionStore,
  cleanupSessionLifecycleArtifacts,
  deleteSessionEntryLifecycle,
  preserveTemporarySessionMapping,
  purgeDeletedAgentSessionEntries,
  resetSessionEntryLifecycle,
  restoreSessionFromCompactionCheckpoint,
  rollbackAgentHarnessSessionEntryLifecycle,
  rollbackPluginOwnedSessionEntryLifecycle,
} from "./session-accessor.lifecycle.js";
export {
  forkSessionAtMessage,
  listSessionBranches,
  resolveSessionTranscriptActiveLeafEntryId,
  rewindSessionToMessage,
  switchSessionBranch,
} from "./session-accessor.message-cut.js";
export {
  commitReplySessionInitialization,
  loadReplySessionInitializationSnapshot,
  persistSessionResetLifecycle,
  SessionInitializationAgentScopeMismatchError,
} from "./session-accessor.reset.js";
export {
  appendTranscriptEvent,
  appendTranscriptEventSync,
  appendTranscriptMessage,
  appendTranscriptMessageSync,
  findTranscriptEvent,
  loadTranscriptEventRowsAfterSeqSync,
  loadTranscriptEvents,
  loadTranscriptEventsSync,
  loadTranscriptHeaderSync,
  loadTranscriptTailEventsSync,
  preflightSessionTranscriptForManualCompact,
  publishTranscriptUpdate,
  readLatestTranscriptAssistantText,
  readTranscriptEventAtSeqSync,
  readTranscriptRawDelta,
  readTranscriptStatsSync,
  replaceTranscriptEvents,
  replaceTranscriptEventsSync,
  rewriteTranscriptEventRowsExact,
  resolveTranscriptSessionKeyBySessionId,
  trimSessionTranscriptForManualCompact,
  withTranscriptWriteLock,
  withTranscriptWriteTransaction,
} from "./session-accessor.transcript.js";
export {
  appendTranscriptMessages,
  persistSessionTranscriptTurn,
} from "./session-accessor.transcript-turn.js";
export {
  isSessionTranscriptProjectionUnavailableError,
  readRecentSessionTranscriptActiveEvents,
  readSessionTranscriptActiveStats,
  readSessionTranscriptBoundedMessageTailPage,
  readRecentSessionTranscriptMessageEvents,
  readSessionTranscriptActiveLeafEvents,
  readSessionTranscriptMessageAnchorPage,
  readSessionTranscriptMessageEventById,
  readSessionTranscriptMessageEventCount,
  readSessionTranscriptMessageEventPage,
  readSessionTranscriptMessageEvents,
  readSessionTranscriptVisibleMessageDelta,
  SessionTranscriptProjectionUnavailableError,
  waitForSessionTranscriptProjection,
} from "./session-accessor.sqlite-active-events.js";
export {
  readSessionTranscriptTitleProbeBatch,
  type SessionTranscriptTitleProbe,
} from "./session-accessor.sqlite-title-probes.js";
export type {
  SessionTranscriptBoundedMessageTailPage,
  SessionTranscriptMessageAnchorPage,
  SessionTranscriptMessageEvent,
  SessionTranscriptMessageEventPage,
} from "./session-accessor.sqlite-active-events.js";
export {
  readSessionTranscriptWatermark,
  readSessionTranscriptWatermarkBatch,
  type SessionTranscriptWatermark,
} from "./session-accessor.sqlite-transcript-watermark.js";
export {
  resolveConcreteSessionStorePath,
  resolveSessionTranscriptReadTarget,
  resolveSessionTranscriptRuntimeReadTarget,
  resolveSessionTranscriptRuntimeTarget,
} from "./session-accessor.transcript-target.js";
