// Shared target sets for config help copy quality tests.

import { MEDIA_AUDIO_FIELD_HELP } from "./media-audio-field-metadata.js";

export const ROOT_SECTIONS = [
  "meta",
  "env",
  "wizard",
  "diagnostics",
  "logging",
  "update",
  "browser",
  "ui",
  "tui",
  "auth",
  "models",
  "nodeHost",
  "agents",
  "tools",
  "bindings",
  "broadcast",
  "attachments",
  "messages",
  "commands",
  "approvals",
  "session",
  "cron",
  "transcripts",
  "hooks",
  "channels",
  "surfaces",
  "discovery",
  "talk",
  "gateway",
  "cloudWorkers",
  "memory",
  "plugins",
] as const;

export const TARGET_KEYS = [
  "memory.citations",
  "memory.backend",
  "memory.qmd.searchMode",
  "memory.qmd.rerank",
  "memory.qmd.searchTool",
  "memory.qmd.scope",
  "memory.qmd.includeDefaultMemory",
  "memory.qmd.command",
  "memory.qmd.paths",
  "memory.qmd.paths.path",
  "memory.qmd.paths.pattern",
  "memory.qmd.paths.name",
  "memory.qmd.sessions.enabled",
  "memory.qmd.sessions.exportDir",
  "memory.qmd.sessions.retentionDays",
  "memory.qmd.limits.maxResults",
  "memory.qmd.limits.maxSnippetChars",
  "memory.qmd.limits.maxInjectedChars",
  "memory.qmd.limits.timeoutMs",
  "memory.search.provider",
  "memory.search.fallback",
  "memory.search.sources",
  "memory.search.extraPaths",
  "memory.search.qmd",
  "memory.search.qmd.extraCollections",
  "memory.search.qmd.extraCollections.path",
  "memory.search.qmd.extraCollections.name",
  "memory.search.qmd.extraCollections.pattern",
  "memory.search.multimodal",
  "memory.search.multimodal.enabled",
  "memory.search.multimodal.modalities",
  "memory.search.multimodal.maxFileBytes",
  "memory.search.remote.baseUrl",
  "memory.search.remote.apiKey",
  "memory.search.remote.headers",
  "memory.search.remote.batch.enabled",
  "memory.search.local.modelPath",
  "memory.search.inputType",
  "memory.search.queryInputType",
  "memory.search.documentInputType",
  "memory.search.outputDimensionality",
  "memory.search.store.vector.extensionPath",
  "memory.search.cache.enabled",
  "models.mode",
  "models.providers.*.auth",
  "models.providers.*.authHeader",
  "models.providers.*.request",
  "gateway.reload.mode",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback",
  "gateway.controlUi.embedSandbox",
  "cron",
  "cron.enabled",
  "cron.webhookToken",
  "cron.webhookSsrfPolicy",
  "cron.webhookSsrfPolicy.dangerouslyAllowPrivateNetwork",
  "cron.webhookSsrfPolicy.allowedHostnames",
  "cron.webhookSsrfPolicy.allowRfc2544BenchmarkRange",
  "cron.webhookSsrfPolicy.allowIpv6UniqueLocalRange",
  "cron.sessionRetention",
  "session",
  "session.scope",
  "session.dmScope",
  "session.identityLinks",
  "session.resetTriggers",
  "session.reset",
  "session.reset.mode",
  "session.reset.atHour",
  "session.reset.idleMinutes",
  "session.resetByType",
  "session.resetByType.direct",
  "session.resetByType.group",
  "session.resetByType.thread",
  "session.resetByChannel",
  "session.store",
  "agents.defaults.typingMode",
  "agents.defaults.typingIntervalSeconds",
  "agents.entries.*.typingMode",
  "session.mainKey",
  "session.sendPolicy",
  "session.sendPolicy.default",
  "session.sendPolicy.rules",
  "session.sendPolicy.rules[].action",
  "session.sendPolicy.rules[].match",
  "session.sendPolicy.rules[].match.channel",
  "session.sendPolicy.rules[].match.chatType",
  "session.sendPolicy.rules[].match.keyPrefix",
  "session.sendPolicy.rules[].match.rawKeyPrefix",
  "session.threadBindings",
  "session.threadBindings.enabled",
  "session.threadBindings.idleHours",
  "session.threadBindings.maxAgeHours",
  "session.threadBindings.spawnSessions",
  "session.threadBindings.defaultSpawnContext",
  "session.maintenance",
  "session.maintenance.mode",
  "session.maintenance.pruneAfter",
  "session.maintenance.maxEntries",
  "session.maintenance.resetArchiveRetention",
  "session.maintenance.maxDiskBytes",
  "session.maintenance.highWaterBytes",
  "approvals",
  "approvals.exec",
  "approvals.exec.enabled",
  "approvals.exec.mode",
  "approvals.exec.agentFilter",
  "approvals.exec.sessionFilter",
  "approvals.exec.targets",
  "approvals.exec.targets[].channel",
  "approvals.exec.targets[].to",
  "approvals.exec.targets[].accountId",
  "approvals.exec.targets[].threadId",
  "nodeHost",
  "nodeHost.agentRuns",
  "nodeHost.agentRuns.claude",
  "nodeHost.agentRuns.claude.enabled",
  "nodeHost.browserProxy",
  "nodeHost.browserProxy.enabled",
  "nodeHost.browserProxy.allowProfiles",
  "nodeHost.mcp",
  "nodeHost.mcp.servers",
  "nodeHost.skills",
  "nodeHost.skills.enabled",
  "attachments",
  "bindings",
  "bindings[].agentId",
  "bindings[].match",
  "bindings[].match.channel",
  "bindings[].match.accountId",
  "bindings[].match.peer",
  "bindings[].match.peer.kind",
  "bindings[].match.peer.id",
  "bindings[].match.guildId",
  "bindings[].match.teamId",
  "bindings[].match.roles",
  "broadcast",
  "broadcast.strategy",
  "broadcast.*",
  "commands",
  "commands.allowFrom",
  "hooks",
  "hooks.enabled",
  "hooks.path",
  "hooks.token",
  "hooks.defaultSessionKey",
  "hooks.allowRequestSessionKey",
  "hooks.allowedSessionKeyPrefixes",
  "hooks.allowedAgentIds",
  "hooks.transformsDir",
  "hooks.mappings",
  "hooks.mappings[].action",
  "hooks.mappings[].wakeMode",
  "hooks.mappings[].channel",
  "hooks.mappings[].transform.module",
  "hooks.gmail",
  "hooks.gmail.pushToken",
  "hooks.gmail.tailscale.mode",
  "hooks.gmail.thinking",
  "hooks.internal",
  "hooks.internal.load.extraDirs",
  "messages",
  "messages.visibleReplies",
  "messages.groupChat",
  "messages.groupChat.mentionPatterns",
  "messages.groupChat.historyLimit",
  "messages.groupChat.unmentionedInbound",
  "messages.groupChat.visibleReplies",
  "messages.queue",
  "messages.queue.mode",
  "messages.queue.byChannel",
  "messages.queue.debounceMsByChannel",
  "messages.queue.cap",
  "messages.queue.drop",
  "messages.inbound",
  "messages.inbound.byChannel",
  "tts",
  "channels",
  "channels.defaults",
  "channels.defaults.groupPolicy",
  "channels.defaults.contextVisibility",
  "channels.defaults.implicitMentions",
  "channels.defaults.implicitMentions.replyToBot",
  "channels.defaults.implicitMentions.quotedBot",
  "channels.defaults.implicitMentions.threadParticipation",
  "channels.defaults.heartbeatVisibility",
  "channels.defaults.heartbeatVisibility.showOk",
  "channels.defaults.heartbeatVisibility.showAlerts",
  "channels.defaults.heartbeatVisibility.useIndicator",
  "channels.defaults.botLoopProtection",
  "channels.defaults.botLoopProtection.enabled",
  "channels.defaults.botLoopProtection.maxEventsPerWindow",
  "channels.defaults.botLoopProtection.windowSeconds",
  "channels.defaults.botLoopProtection.cooldownSeconds",
  "gateway",
  "gateway.mode",
  "gateway.bind",
  "gateway.auth.mode",
  "gateway.tailscale.mode",
  "gateway.tools.allow",
  "gateway.tools.deny",
  "gateway.tls.enabled",
  "gateway.tls.autoGenerate",
  "gateway.http",
  "gateway.http.endpoints",
  "browser",
  "browser.enabled",
  "browser.cdpUrl",
  "browser.headless",
  "browser.noSandbox",
  "browser.profiles",
  "browser.profiles.*.userDataDir",
  "browser.profiles.*.driver",
  "browser.profiles.*.attachOnly",
  "tools",
  "tools.allow",
  "tools.deny",
  "tools.exec",
  "tools.exec.host",
  "tools.exec.mode",
  "tools.exec.node",
  "tools.agentToAgent.enabled",
  "tools.elevated.enabled",
  "tools.elevated.allowFrom",
  "tools.subagents.tools",
  "tools.sandbox.tools",
  "discovery",
  "discovery.wideArea.domain",
  "discovery.mdns",
  "discovery.mdns.mode",
  "gateway.controlUi.embedSandbox",
  "talk",
  "talk.consultFastMode",
  "talk.interruptOnSpeech",
  "talk.silenceTimeoutMs",
  "talk.consultThinkingLevel",
  "meta",
  "env",
  "env.shellEnv",
  "env.shellEnv.enabled",
  "env.shellEnv.timeoutMs",
  "env.vars",
  "wizard",
  "diagnostics",
  "diagnostics.otel",
  "diagnostics.cacheTrace",
  "logging",
  "logging.level",
  "logging.file",
  "logging.consoleLevel",
  "logging.consoleStyle",
  "logging.redactPatterns",
  "update",
  "ui",
  "ui.assistant",
  "plugins",
  "plugins.enabled",
  "plugins.allow",
  "plugins.deny",
  "plugins.load",
  "plugins.load.paths",
  "plugins.slots",
  "plugins.entries",
  "plugins.entries.*.enabled",
  "plugins.entries.*.hooks",
  "plugins.entries.*.hooks.allowPromptInjection",
  "plugins.entries.*.hooks.allowConversationAccess",
  "plugins.entries.*.hooks.timeoutMs",
  "plugins.entries.*.hooks.timeouts",
  "plugins.entries.*.subagent",
  "plugins.entries.*.subagent.allowModelOverride",
  "plugins.entries.*.subagent.allowedModels",
  "plugins.entries.*.llm",
  "plugins.entries.*.llm.allowModelOverride",
  "plugins.entries.*.llm.allowedModels",
  "plugins.entries.*.llm.allowedCompletionModels",
  "plugins.entries.*.llm.allowAuthProfileOverride",
  "plugins.entries.*.llm.allowAgentIdOverride",
  "plugins.entries.*.apiKey",
  "plugins.entries.*.env",
  "plugins.entries.*.config",
  "auth",
  "models",
  "models.providers",
  "models.providers.*.baseUrl",
  "models.providers.*.apiKey",
  "models.providers.*.api",
  "models.providers.*.contextWindow",
  "models.providers.*.contextTokens",
  "models.providers.*.maxTokens",
  "models.providers.*.region",
  "models.providers.*.headers",
  "models.providers.*.models",
  "agents",
  "agents.defaults",
  "agents.entries",
  "agents.defaults.compaction",
  "agents.defaults.compaction.mode",
  "agents.defaults.compaction.provider",
  "agents.defaults.compaction.thinkingLevel",
  "agents.defaults.compaction.keepRecentTokens",
  "agents.defaults.compaction.identifierPolicy",
  "agents.defaults.compaction.recentTurnsPreserve",
  "agents.defaults.compaction.qualityGuard",
  "agents.defaults.compaction.qualityGuard.enabled",
  "agents.defaults.compaction.qualityGuard.maxRetries",
  "agents.defaults.compaction.midTurnPrecheck",
  "agents.defaults.compaction.midTurnPrecheck.enabled",
  "agents.defaults.compaction.postCompactionSections",
  "agents.defaults.compaction.timeoutSeconds",
  "agents.defaults.compaction.model",
  "agents.defaults.compaction.maxActiveTranscriptBytes",
  "agents.defaults.compaction.memoryFlush",
  "agents.defaults.compaction.memoryFlush.enabled",
  "agents.defaults.compaction.memoryFlush.model",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens",
] as const;

export const ENUM_EXPECTATIONS: Record<string, string[]> = {
  "skills.workshop.autonomous.mode": ['"off"', '"propose"', '"auto"'],
  "memory.citations": ['"auto"', '"on"', '"off"'],
  "memory.backend": ['"builtin"', '"qmd"'],
  "memory.qmd.searchMode": ['"query"', '"search"', '"vsearch"'],
  "models.mode": ['"merge"', '"replace"'],
  "models.providers.*.auth": ['"api-key"', '"token"', '"oauth"', '"aws-sdk"'],
  "gateway.reload.mode": ['"off"', '"hybrid"'],
  "approvals.exec.mode": ['"session"', '"targets"', '"both"'],
  "bindings[].match.peer.kind": ['"direct"', '"group"', '"channel"', '"dm"'],
  "broadcast.strategy": ['"parallel"', '"sequential"'],
  "hooks.mappings[].action": ['"wake"', '"agent"'],
  "hooks.mappings[].wakeMode": ['"now"', '"next-heartbeat"'],
  "hooks.gmail.tailscale.mode": ['"off"', '"serve"', '"funnel"'],
  "hooks.gmail.thinking": ['"off"', '"minimal"', '"low"', '"medium"', '"high"'],
  "messages.queue.mode": ['"steer"', '"followup"', '"collect"', '"interrupt"'],
  "messages.queue.drop": ['"old"', '"new"', '"summarize"'],
  "channels.defaults.groupPolicy": ['"open"', '"disabled"', '"allowlist"'],
  "channels.defaults.contextVisibility": ['"all"', '"allowlist"', '"allowlist_quote"'],
  "gateway.mode": ['"local"', '"remote"'],
  "gateway.bind": ['"auto"', '"lan"', '"loopback"', '"custom"', '"tailnet"'],
  "gateway.auth.mode": ['"none"', '"token"', '"password"', '"trusted-proxy"'],
  "gateway.tailscale.mode": ['"off"', '"serve"', '"funnel"'],
  "browser.profiles.*.driver": ['"openclaw"', '"clawd"', '"existing-session"'],
  "discovery.mdns.mode": ['"off"', '"minimal"', '"full"'],
  "diagnostics.otel.protocol": ['"http/protobuf"'],
  "diagnostics.otel.logsExporter": ['"otlp"', '"stdout"', '"both"'],
  "logging.level": ['"silent"', '"fatal"', '"error"', '"warn"', '"info"', '"debug"', '"trace"'],
  "logging.consoleLevel": [
    '"silent"',
    '"fatal"',
    '"error"',
    '"warn"',
    '"info"',
    '"debug"',
    '"trace"',
  ],
  "logging.consoleStyle": ['"pretty"', '"json"'],
  "update.channel": ['"stable"', '"extended-stable"', '"beta"', '"dev"'],
  "agents.defaults.compaction.mode": ['"default"', '"safeguard"'],
  "agents.defaults.compaction.thinkingLevel": [
    '"off"',
    '"minimal"',
    '"low"',
    '"medium"',
    '"high"',
    '"xhigh"',
    '"adaptive"',
    '"max"',
    '"ultra"',
  ],
  "agents.defaults.compaction.identifierPolicy": ['"strict"', '"off"'],
};

export const TOOLS_HOOKS_TARGET_KEYS = [
  "hooks.gmail.account",
  "hooks.gmail.allowUnsafeExternalContent",
  "hooks.gmail.hookUrl",
  "hooks.gmail.includeBody",
  "hooks.gmail.label",
  "hooks.gmail.model",
  "hooks.gmail.serve",
  "hooks.gmail.subscription",
  "hooks.gmail.tailscale",
  "hooks.gmail.topic",
  "hooks.internal.entries",
  "hooks.internal.load",
  "hooks.mappings[].allowUnsafeExternalContent",
  "hooks.mappings[].deliver",
  "hooks.mappings[].id",
  "hooks.mappings[].match",
  "hooks.mappings[].messageTemplate",
  "hooks.mappings[].model",
  "hooks.mappings[].name",
  "hooks.mappings[].textTemplate",
  "hooks.mappings[].thinking",
  "hooks.mappings[].transform",
  "tools.alsoAllow",
  "tools.byProvider",
  "tools.exec.approvalRunningNoticeMs",
  "tools.exec.strictInlineEval",
  "tools.exec.commandHighlighting",
  "tools.links.enabled",
  "tools.links.maxLinks",
  "tools.links.models",
  "tools.links.scope",
  "tools.links.timeoutSeconds",
  ...Object.keys(MEDIA_AUDIO_FIELD_HELP),
  "tools.media.concurrency",
  "tools.media.image.enabled",
  "tools.media.image.preferredModel",
  "tools.media.image.maxBytes",
  "tools.media.image.maxChars",
  "tools.media.image.prompt",
  "tools.media.image.timeoutSeconds",
  "tools.media.image.scope",
  "tools.media.image.attachments",
  "tools.media.models",
  "tools.media.video.enabled",
  "tools.media.video.preferredModel",
  "tools.media.video.maxBytes",
  "tools.media.video.maxChars",
  "tools.media.video.prompt",
  "tools.media.video.timeoutSeconds",
  "tools.media.video.scope",
  "tools.media.video.attachments",
  "tools.profile",
] as const;

export const CHANNELS_AGENTS_TARGET_KEYS = [
  "memory.search.enabled",
  "memory.search.model",
  "memory.search.query.maxResults",
  "memory.search.query.minScore",
  "agents.defaults.workspace",
  "agents.entries.*.tools.alsoAllow",
  "agents.entries.*.tools.byProvider",
  "agents.entries.*.tools.message.crossContext.allowAcrossProviders",
  "agents.entries.*.tools.message.crossContext.allowWithinProvider",
  "agents.entries.*.tools.profile",
  "channels.mattermost",
] as const;

export const FINAL_BACKLOG_TARGET_KEYS = [
  "browser.evaluateEnabled",
  "browser.snapshotDefaults",
  "browser.snapshotDefaults.mode",
  "browser.ssrfPolicy",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork",
  "browser.ssrfPolicy.allowedHostnames",
  "browser.ssrfPolicy.allowedHostnames",
  "diagnostics.enabled",
  "diagnostics.otel.enabled",
  "diagnostics.otel.endpoint",
  "diagnostics.otel.flushIntervalMs",
  "diagnostics.otel.headers",
  "diagnostics.otel.logsEndpoint",
  "diagnostics.otel.logs",
  "diagnostics.otel.logsExporter",
  "diagnostics.otel.metricsEndpoint",
  "diagnostics.otel.metrics",
  "diagnostics.otel.sampleRate",
  "diagnostics.otel.serviceName",
  "diagnostics.otel.tracesEndpoint",
  "diagnostics.otel.traces",
  "gateway.remote.password",
  "gateway.remote.token",
  "skills.load.allowSymlinkTargets",
  "skills.load.extraDirs",
  "skills.load.watch",
  "skills.workshop.allowSymlinkTargetWrites",
  "ui.assistant.avatar",
  "ui.assistant.name",
  "ui.seamColor",
] as const;
