// Covers trust-plan unwrapping for exec command wrappers.
import { describe, expect, test } from "vitest";
import { resolveExecWrapperTrustPlan } from "./exec-wrapper-trust-plan.js";

describe("resolveExecWrapperTrustPlan", () => {
  test.each([
    {
      name: "unwraps command argv carriers before evaluating allowlist policy",
      enabled: process.platform !== "win32",
      argv: ["command", "curl", "https://example.invalid"],
      expected: {
        argv: ["curl", "https://example.invalid"],
        policyArgv: ["curl", "https://example.invalid"],
        wrapperChain: ["command"],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "does not unwrap path-qualified command tokens as shell builtins",
      enabled: process.platform !== "win32",
      argv: ["/tmp/openclaw-test/command", "curl", "https://example.invalid"],
      expected: {
        argv: ["/tmp/openclaw-test/command", "curl", "https://example.invalid"],
        policyArgv: ["/tmp/openclaw-test/command", "curl", "https://example.invalid"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "does not unwrap command tokens on Windows",
      enabled: true,
      argv: ["command", "curl", "https://example.invalid"],
      platform: "win32" as const,
      expected: {
        argv: ["command", "curl", "https://example.invalid"],
        policyArgv: ["command", "curl", "https://example.invalid"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "unwraps command argv carriers through transparent dispatch wrappers",
      enabled: process.platform !== "win32",
      argv: ["env", "command", "--", "python3", "/tmp/run.py"],
      expected: {
        argv: ["python3", "/tmp/run.py"],
        policyArgv: ["python3", "/tmp/run.py"],
        wrapperChain: ["env", "command"],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "unwraps builtin argv carriers before evaluating allowlist policy",
      enabled: process.platform !== "win32",
      argv: ["builtin", "printf", "ok"],
      expected: {
        argv: ["printf", "ok"],
        policyArgv: ["printf", "ok"],
        wrapperChain: ["builtin"],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "unwraps exec argv carriers before evaluating allowlist policy",
      enabled: process.platform !== "win32",
      argv: ["exec", "-a", "friendly-name", "bash", "/tmp/run.sh"],
      expected: {
        argv: ["bash", "/tmp/run.sh"],
        policyArgv: ["bash", "/tmp/run.sh"],
        wrapperChain: ["exec"],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: null,
      },
    },
    {
      name: "keeps startup-file shell wrappers opaque before evaluating allowlist policy",
      enabled: true,
      argv: ["tcsh", "-c", "echo hi"],
      expected: {
        argv: ["tcsh", "-c", "echo hi"],
        policyArgv: ["tcsh", "-c", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: null,
      },
    },
    {
      name: "recognizes nushell command flags before evaluating allowlist policy",
      enabled: true,
      argv: ["nu", "--commands", "echo hi"],
      expected: {
        argv: ["nu", "--commands", "echo hi"],
        policyArgv: ["nu", "--commands", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "recognizes nushell execute flags before evaluating allowlist policy",
      enabled: true,
      argv: ["nu", "--execute", "echo hi"],
      expected: {
        argv: ["nu", "--execute", "echo hi"],
        policyArgv: ["nu", "--execute", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "omits nushell config inline-value startup payloads from trust plans",
      enabled: true,
      argv: ["nu", "--config=/tmp/evil.nu", "--commands", "echo hi"],
      expected: {
        argv: ["nu", "--config=/tmp/evil.nu", "--commands", "echo hi"],
        policyArgv: ["nu", "--config=/tmp/evil.nu", "--commands", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: null,
      },
    },
    {
      name: "omits nushell env-config startup payloads from trust plans",
      enabled: true,
      argv: ["nu", "--env-config", "/tmp/evil.nu", "--commands", "echo hi"],
      expected: {
        argv: ["nu", "--env-config", "/tmp/evil.nu", "--commands", "echo hi"],
        policyArgv: ["nu", "--env-config", "/tmp/evil.nu", "--commands", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: null,
      },
    },
    {
      name: "recognizes yash cmdline flags before evaluating allowlist policy",
      enabled: true,
      argv: ["yash", "--cmdline", "echo hi"],
      expected: {
        argv: ["yash", "--cmdline", "echo hi"],
        policyArgv: ["yash", "--cmdline", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "recognizes clustered yash command flags before evaluating allowlist policy",
      enabled: true,
      argv: ["yash", "-xc", "echo hi"],
      expected: {
        argv: ["yash", "-xc", "echo hi"],
        policyArgv: ["yash", "-xc", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "fails closed for non-executing command argv carrier queries",
      enabled: process.platform !== "win32",
      argv: ["command", "-v", "curl"],
      expected: {
        argv: ["command", "-v", "curl"],
        policyArgv: ["command", "-v", "curl"],
        wrapperChain: [],
        policyBlocked: true,
        blockedWrapper: "command",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "fails closed for command carriers that request default PATH lookup",
      enabled: process.platform !== "win32",
      argv: ["command", "-p", "curl", "https://example.invalid"],
      expected: {
        argv: ["command", "-p", "curl", "https://example.invalid"],
        policyArgv: ["command", "-p", "curl", "https://example.invalid"],
        wrapperChain: [],
        policyBlocked: true,
        blockedWrapper: "command",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "unwraps transparent caffeinate wrappers before shell policy checks",
      enabled: process.platform !== "win32",
      argv: ["/usr/bin/caffeinate", "-d", "-w", "42", "sh", "-c", "echo hi"],
      expected: {
        argv: ["sh", "-c", "echo hi"],
        policyArgv: ["sh", "-c", "echo hi"],
        wrapperChain: ["caffeinate"],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "unwraps dispatch wrappers and shell multiplexers into one trust plan",
      enabled: process.platform !== "win32",
      argv: ["/usr/bin/time", "-p", "busybox", "sh", "-c", "echo hi"],
      expected: {
        argv: ["sh", "-c", "echo hi"],
        policyArgv: ["busybox", "sh", "-c", "echo hi"],
        wrapperChain: ["time", "busybox"],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "blocks script wrappers before evaluating nested shell payloads",
      enabled: process.platform === "darwin" || process.platform === "freebsd",
      argv: ["/usr/bin/script", "-q", "/dev/null", "sh", "-c", "echo hi"],
      expected: {
        argv: ["/usr/bin/script", "-q", "/dev/null", "sh", "-c", "echo hi"],
        policyArgv: ["/usr/bin/script", "-q", "/dev/null", "sh", "-c", "echo hi"],
        wrapperChain: [],
        policyBlocked: true,
        blockedWrapper: "script",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "unwraps sandbox-exec wrappers before evaluating nested shell payloads",
      enabled: process.platform !== "win32",
      argv: ["/usr/bin/sandbox-exec", "-p", "(allow default)", "sh", "-c", "echo hi"],
      expected: {
        argv: ["sh", "-c", "echo hi"],
        policyArgv: ["sh", "-c", "echo hi"],
        wrapperChain: ["sandbox-exec"],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: "echo hi",
      },
    },
    {
      name: "keeps package-manager exec argv as the execution trust target",
      enabled: true,
      argv: ["pnpm", "--reporter", "silent", "exec", "--", "tsx", "./run.ts"],
      expected: {
        argv: ["pnpm", "--reporter", "silent", "exec", "--", "tsx", "./run.ts"],
        policyArgv: ["pnpm", "--reporter", "silent", "exec", "--", "tsx", "./run.ts"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "keeps package-manager shell-call mode outside generic wrapper policy",
      enabled: true,
      argv: ["npx", "--call", "sh -c 'echo hi'"],
      expected: {
        argv: ["npx", "--call", "sh -c 'echo hi'"],
        policyArgv: ["npx", "--call", "sh -c 'echo hi'"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "omits startup shell inline payloads from trust plans",
      enabled: process.platform !== "win32",
      argv: ["bash", "--login", "-c", "echo hi"],
      expected: {
        argv: ["bash", "--login", "-c", "echo hi"],
        policyArgv: ["bash", "--login", "-c", "echo hi"],
        wrapperChain: [],
        policyBlocked: false,
        shellWrapperExecutable: true,
        shellInlineCommand: null,
      },
    },
    {
      name: "fails closed for unsupported shell multiplexer applets",
      enabled: true,
      argv: ["busybox", "sed", "-n", "1p"],
      expected: {
        argv: ["busybox", "sed", "-n", "1p"],
        policyArgv: ["busybox", "sed", "-n", "1p"],
        wrapperChain: [],
        policyBlocked: true,
        blockedWrapper: "busybox",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "fails closed when outer-wrapper depth overflows",
      enabled: true,
      argv: ["nohup", "timeout", "5s", "busybox", "sh", "-lc", "echo hi"],
      depth: 2,
      expected: {
        argv: ["busybox", "sh", "-lc", "echo hi"],
        policyArgv: ["busybox", "sh", "-lc", "echo hi"],
        wrapperChain: ["nohup", "timeout"],
        policyBlocked: true,
        blockedWrapper: "busybox",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
    {
      name: "keeps the blocked dispatch argv as the policy target after transparent unwraps",
      enabled: process.platform !== "win32",
      argv: ["/usr/bin/time", "-p", "/usr/bin/env", "FOO=bar", "sh", "-lc", "echo hi"],
      expected: {
        argv: ["/usr/bin/env", "FOO=bar", "sh", "-lc", "echo hi"],
        policyArgv: ["/usr/bin/env", "FOO=bar", "sh", "-lc", "echo hi"],
        wrapperChain: [],
        policyBlocked: true,
        blockedWrapper: "env",
        shellWrapperExecutable: false,
        shellInlineCommand: null,
      },
    },
  ])("$name", ({ enabled, argv, depth, platform, expected }) => {
    if (!enabled) {
      return;
    }
    expect(resolveExecWrapperTrustPlan(argv, depth, platform)).toEqual(expected);
  });
});
